### PR TITLE
Build for more platforms

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Review by isuruf — APPROVED** [review]

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by saraedum** [comment]
This needs https://github.com/conda-forge/primesieve-feedstock/pull/22.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
